### ISSUE TITLE
Impressum Landing Page

### ISSUE THREAD

**Issue by tilladams** [mundialis/fossgis2018#2]
Vermutlich brauchen wir für die Landing Page auch einen Disclaimer und ein Impressum, ich schätze das der Link auf mundialis.de da nicht ausreichen wird.

**Comment by mmacata** [comment]
Siehst du noch Handlungsbedarf? https://mundialis.github.io/fossgis2018/

**Comment by neteler** [comment]
Kann geschlossen werden.
